apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecoscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecoscale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ecoscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ecoscale.selectorLabels" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 4 }}
        {{- end }}
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ .name | default (include "ecoscale.serviceAccountName" $) }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: ECOSCALE_ADDR
              value: ":{{ .Values.service.port }}"
            - name: ECOSCALE_INTERVAL
              value: {{ .Values.interval | quote }}
            - name: ECOSCALE_CARBON_THRESHOLD
              value: {{ .Values.carbonThreshold | quote }}
            - name: ECOSCALE_IN_CLUSTER
              value: "true"
            - name: ECOSCALE_CARBON_API
              value: {{ .Values.carbonAPI | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
